name: Build prerelease GameNative Parallel

on:
  workflow_dispatch:
    inputs:
      upstream_tag:
        description: Upstream prerelease tag to build (required)
        required: true
        type: string
  workflow_call:
    inputs:
      upstream_tag:
        description: Upstream prerelease tag to build
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/parallel-build.yml
    with:
      upstream_tag: ${{ inputs.upstream_tag }}
      prerelease: true
    secrets: inherit
